# NeuroMorse experiment configuration.
dataset: NeuroMorse
experiment_name: neuromorse
num_runs: 1
seed: 42
device: auto
data_root: ./data
batch_size: 50
time_window: 8
spat_ds_fac: 1.0
num_crop_pixel: 0
seq_len: 100
padding_size: null
slice_input_by_amount: false
num_slices: 1
include_zero_slice: false
slicing_thrs: [0.5]
slicing_thrs_maxs: null
aug_og_data: false
aug_kwargs: null
denoise_data: false
denoise_mode: tonic
task_type: null
jitter_level: none  # Options: none, low, high
dropout_level: none  # Options: none, low, high
poisson_level: none  # Options: none, low, high
permute_data: false
permutation_seed: null

rewiring: true
supervised: true
continue_rewiring_from_checkpoint: false
continue_supervised_from_checkpoint: false
load_checkpoint_folder: null
num_searching_units: 30000
thr_factor: 30
thr_low: -90
thr_high: 450
penalty_fac: 2.0
class_selectivity_threshold: 0.025
selectivity_gap_to_other_classes: 0.03
experiment_mode: std

num_hidden_layer: 1
num_hidden_units: 1000
num_spines: 5
min_num_spines: 2
max_seq_len: null
spike_acceptance_window: 2
parallel_sequences: true
refrac_period: false
output_bias: false
output_decoder: last
lr: 0.001
lr_scheduled: false
lr_decay: 15
lr_update_freq: 5
l2_regu: 0
dropout: 0.0
num_workers: 0
max_rewiring_epochs: 10000000
max_supervised_epochs: 1000000
early_stopping_patience: 30
pruning_level: 0.7
bit_width: 8
